### PR TITLE
Draft 1: Cart and Stats Bar

### PR DESCRIPTION
**Pull request by iksheth**
Making changes on Bento 4.0 FE to match Cart, NavBar, and Stats bar styles. Cart: Download Manifest not working.
NavBar: Done ✅
StatsBar: Styling Issues.

### CODE REVIEW

**Comment by huuaho** [comment]
Differences I found on the branch from the current implementation
- Font on current CDS is Nunito, the branch is using Roboto
- Download manifest button does not work
- Current CDS Files table has pagination on both top and bottom but branch implementation has only bottom pagination

**Comment by huuaho** [comment]
NOTE: This PR is for the tickets [CDS-513](https://tracker.nci.nih.gov/browse/CDS-513) (Stats bar) and [CDS-518](https://tracker.nci.nih.gov/browse/CDS-518) (Cart Table).


In regards to 518, there is a bit of confusion as to what the first requirement is, but will mark it as not fulfilled.

In regards to 513, 

- the landing page's stats bar does reroute to the data page for participants, samples, files but does not auto select the tab for samples and files as described in the requirements.

**Review by huuaho — APPROVED** [review]
we will need to circle back and address the requirements

**Comment by iksheth** [comment]
Keeping CDS-513 for Future work.

**Pull request merged**
